// File: output_files/RAM.v
// Generated by MyHDL 1.0dev
// Date: Wed Jun  1 06:14:38 2016


`timescale 1ns/10ps

module RAM (
    d,
    waddr,
    raddr,
    we,
    clk,
    q
);
// default addr width 6, data width 12

input [9:0] d;
input [5:0] waddr;
input [5:0] raddr;
input we;
input clk;
output [9:0] q;
wire [9:0] q;

reg [5:0] read_addr;

reg [9:0] mem [0:64-1];





assign q = mem[read_addr];


always @(posedge clk) begin: RAM_BEH_WRITE
    read_addr <= raddr;
    if (we) begin
        mem[waddr] <= d;
    end
end

endmodule
