
# invoke the test with the python 
# nosetests --verbosity=2 --with-coverage
all:
	python test_jpegenc.py

clean:
	rm -f bench*
	rm -f bench*.v
	rm -f bench*.vhd
	rm -f *.o
	rm -f *.vcd*
	rm -f *.log	
